### ISSUE TITLE
adding a new index document blocks previous index update until indexing is done

### ISSUE THREAD

**Issue by emig** [rnewson/couchdb-lucene#213]
In a setup having a couchdb-lucene indexing document in a db:
- _design/search-version:0.0.5  at update_seq **X**

When adding a new one:
- _design/search-version:0.1.4

old document stops updating and gets blocked at  update_seq **X** until new document has reached **X**

more info:
- couchdb-lucene v1.0.2
- couchdb 1.5
- using couchdb-external-hook.py

**Comment by rnewson** [comment]
This is by design, though I do see that it's not a great design. The _changes feed is per database and all interested indexes feed off that. The motivation was to optimize the number of changes feeds being pulled from couchdb at a time. This is the unintended side-effect.

**Comment by emig** [comment]
Closing, Thank you.
