### ISSUE TITLE
Search within date range filtering in couchdb lucene search?

### ISSUE THREAD

**Issue by soundari** [rnewson/couchdb-lucene#214]
In json document, We have start date and end date.

For ex : {"start-date" : "2014-12-05","end-date":"2015-03-15"}

I want to retrieve the records exist between the range of start-date and end-date.How can implement above scenerio in couchdb lucene search?

Kindly help me out.

**Comment by rnewson** [comment]
Hi, have a quick look at the README at https://github.com/rnewson/couchdb-lucene, there's a section on range queries.

**Comment by rnewson** [comment]
Closing as not an "issue".
