### ISSUE TITLE
Problems searching index using dates

### ISSUE THREAD

**Issue by elwin1234** [rnewson/couchdb-lucene#220]
Hi,

According to the documentation the following formats are valid for date search:

field&lt;date>:[from TO to] where from and to match any of these patterns: <code>"yyyy-MM-dd'T'HH:mm:ssZ"</code>, <code>yyyy-MM-dd'T'HH:mm:ss</code>, <code>"yyyy-MM-ddZ"</code>, <code>"yyyy-MM-dd"</code>, <code>"yyyy-MM-dd'T'HH:mm:ss.SSSZ"</code>, <code>"yyyy-MM-dd'T'HH:mm:ss.SSS"</code>. So, in order to search for articles published in July, you would issue a following query: <code>published_at&lt;date&gt;:["2010-07-01T00:00:00"+TO+"2010-07-31T23:59:59"]</code>

I created the following index
```javascript
..
document.add(
  new Date(), {
    "field":"indexDate",
    "store":"yes",
    "type":"date"
  }
);
..
```

Querying <code>?q=indexDate<date>:["2015-05-21T13:00:30"+TO+"2015-05-21T15:00:30"]</code> works, where
<code>?q=indexDate<date>:["2015-05-21T13:00:30Z"+TO+"2015-05-21T15:00:30Z"]</code> gives me the following error:

<code>
Bad query syntax: Cannot parse 'indexDate<date>:[\"2015-05-21T13:00:30Z\" TO \"2015-05-21T15:00:30Z\"]': Unable to parse the date: 2015-05-21T13:00:30Z
</code>

Furthermore I expect that the times you provide in search are in UTC format, but they seem to use local times. 

Can I add a timezone offset to my search query?

**Comment by rnewson** [comment]
Ah, 'Z' here stands for timezone, not a literal Z. See https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html for details but you want to say 2015-05-21T13:00:30-0500 or similar.

**Comment by elwin1234** [comment]
Ah, thanks! Great!
