### ISSUE TITLE
paging support

### ISSUE THREAD

**Issue by imadulhaque** [rnewson/couchdb-lucene#223]
Hi,
I want to do a search with filtering as paging. I was not able to find a good example for that. Plus I would also want to jump at some random page for search with filter. Is it possible to do with lucene,

Will really appreciate any help.
Thanks.

**Comment by rnewson** [comment]
jumping to a random page is not generally a good idea for lucene, but if page numbers are low you can do it (with 'skip' and 'limit').

**Comment by imadulhaque** [comment]
what sort of figure would you consider low for page numbers? what impact does it have if pages are large in number.

**Comment by rnewson** [comment]
In order to find page X, the results for pages 1-X must be known too (and then discarded), so 'deep' pagination (using skip) is a memory hog, getting worse the deeper you go. It'll depend on your systems as to how far you can go, but you now know what to look for. :)

**Comment by imadulhaque** [comment]
@rnewson thanks for your response.
