### ISSUE TITLE
Couchdb lucene does not respond to port 5984 and shows error "undefined index: reason"

### ISSUE THREAD

**Issue by ramonchristophermorales** [rnewson/couchdb-lucene#224]
Hi rnewson,

I am having a problem in accessing couchdb-lucene properly, and well the story goes like this:

Before the problem occurred, the old developer developed a project that is running perfectly on couchdb-lucene. As time goes by the couchdb required larger space, the client tried to upgrade the storage space for the database. Then client accidentally deleted parts of the project that includes the couch database file, ini configurations and the couchdb-lucene itself. 

We have re-installed the couchdb-lucene, put up back the configuration files in the ini, restart couchdb. The real problem is when I am trying to make a query against it using curl, it returns either a 404 or 500 response, and now the application that I am trying to fix responds "Undefined index: reason" on html view.

**Some info that might be helpful**

Server: Debian GNU/Linux 7

Language: PHP

Framework: Laravel

CouchDB version: 1.6.1

CouchDB-Lucene version: 1.0.2-SNAPSHOT

**Local.ini**

    [couchdb]
    ;max_document_size = 4294967296
    uuid = add1dea463fa3e52a7d719fb99277610
    os_process_timeout=60000
    
    [httpd]
    port = 5985
    ;bind_address = 127.0.0.1
    
    [httpd_global_handlers]
    _fti = {couch_httpd_proxy, handle_proxy_req, <<"http://127.0.0.1:5985">>}
    
    [ssl]
    ssl_certificate_max_depth = 1
    
    [external]
    fti= /usr/bin/python /root/couchdb-lucene/couchdb-lucene/couchdb-external-hook.py
    
    [httpd_db_handlers]
    _fti = {couch_httpd_external, handle_external_req, <<"fti">>}
    
    [compaction_daemon]
    min_file_size = 21474836480
    
    [compaction]
    _default = [{db_fragmentation, "70%"}, {view_fragmentation, "60%"}, {from, "23:00"}, {to, "04:00"}]

**curls and responses**

    curl localhost:4807
    - {"couchdb":"Welcome","uuid":"add1dea463fa3e52a7d719fb99277610","version":"1.6.1","vendor":{"name":"The Apache Software Foundation","version":"1.6.1"}}
    
    curl localhost:5985
    curl localhost:5985/dbname
    curl localhost:5985/_fti
    curl localhost:5985/_config
    - 
    {"couchdb-lucene":"Welcome","version":"1.0.2-SNAPSHOT"}
    
    curl localhost:5984
    curl localhost:5984/_config
    - 
    curl: (7) couldn't connect to host
    
    curl localhost:5985/insightout/_fti/_design/lucene/device_reading?q=couchDbId%3A%222708e7c7a5479895391f419c58b5def6%22+AND+sort_readon%3A%5B1441423093+TO+1441423993%5D
    -
    {"code":500}

I also tried 1.1.0-SNAPSHOT, same results.

Hope you could help me out, thanks!

**Comment by rnewson** [comment]
Hi. Port 5984 is couchdb itself, can you check couch.log to see why it's failing to start?

**Comment by rnewson** [comment]
oh, silly me, you have moved couchdb to port 4807, you will need to tell couchdb-lucene about this (or change it back to its IANA registered port value of 5984);

in couchdb-lucene.ini

[local]
url = http://localhost:4807/

**Comment by ramonchristophermorales** [comment]
Hi, thanks for that info, but I guess I will keep the 4807 in replacement of 5984 for some reason. But the most important thing is that when I try tor run normal queries (example above)  on 5985, it responded error with 500. According to what I know, error 500 has something to do with the configurations. When I run bin/run, it returns a message of "Accepting connections with SelectChannelConnector@localhost:5985" and idk if thats ok. And lastly, my site responds "Undefined index: reason" that I should expect as a response to as why the error shows in the site, I think it has something to do with the query. 

Please help.

**Comment by rnewson** [comment]
Did you change couchdb-lucene.ini and restart it yet? couchdb-lucene needs to contact couchdb to function, and it assumes it's on the same host on port 5984 by default. You need to change the config file if you're sticking with port 4807.

**Comment by ramonchristophermorales** [comment]
Yes I did change couchdb-lucene and pointed it to 4807 and tested it but the still fails, the system returns 500 error that says "Undefined index: reason" and don't know the reason why when viewing from the browser.

Anyways I did some further configurations and debugging and run the application one more time and it run perfectly, I can't remember what I have done but it is working now.

Anyways thanks for your support and I followed your instructions on how to deal with this. I really appreciate it.

**Comment by rnewson** [comment]
:)

**Comment by tmustafa123** [comment]
hey !

**Comment by tmustafa123** [comment]
I am facing some issue .

**Comment by tmustafa123** [comment]
HTTP Error with status 500 occurred while requesting /_fti/local/insightout/_design/lucene/device_reading?q=couchDbId%3A%222708e7c7a5479895391f419c58b5def6%22&sort=sort_readon%3Cint%3E&limit=1. Error: error {conn_failed,{error,econnrefused}} (View: /Applications/MAMP/htdocs/insapp/app/views/workspace/index.blade.php)
im stuck here right now . Kindly guide me where I might be going wrong

**Comment by rnewson** [comment]
@tmustafa123 is it related to this issue? If not, please create a new issue.
