### ISSUE TITLE
optimize, expunge and cleanup calls returns bad_request

### ISSUE THREAD

**Issue by drlinux** [rnewson/couchdb-lucene#232]
When I call optimize, expunge or cleanup actions via curl or browser I've got following error:

Example url:  (using httpd_global_handlers)

```
$ curl -X POST "http://localhost:5985/_fti/local/trades/_design/search/by_all/_optimize"

{"reason":"bad_request","code":400}

$ curl "http://localhost:5985/_fti/local/trades/_design/search/by_all/_optimize"

{"reason":"bad_request","code":400}

```

Am I missing something?

**Comment by rnewson** [comment]
You're hitting the wrong port. :)

The _fti bit is where couchdb-lucene is hooked into couchdb, so try this on port 5984.

if you want to go direct to couchdb-lucene, on port 5985, you should omit the _fti/local part of the url.

**Comment by drlinux** [comment]
thanks dude, it works ;)
