### ISSUE TITLE
Manually trigger full index rebuild?

### ISSUE THREAD

**Issue by kr428** [rnewson/couchdb-lucene#233]
Folks, for upgrading to "recent versions" of couchdb-lucene, I wanted to automatically remove and trigger a rebuild of the whole index structure to make sure this doesn't happen when the system is supposed to be "online" and respond fast. Is there some way to, similar to _optimize or _expunge, manually trigger an index rebuild? Will querying the index do just this, as long as it's missing?
TIA,
Kristian

**Comment by rnewson** [comment]
You can do the same trick as we document for couchdb views: https://wiki.apache.org/couchdb/How_to_deploy_view_changes_in_a_live_environment

In this case, to ensure a clean build, you need to make some non-functional change to your index code (add a comment, for example). This will cause couchdb-lucene to calculate a different output directory name and then build that index from scratch.

When it's built, you can then PUT that exact code into your original design document, and it'll instantly update to point to the new index.

**Comment by kr428** [comment]
Thanks, I'll have a look at this option too. My current approach (as we're setting up a new, larger machine for couchdb+lucene) is / was to set up a new CouchDB with Lucene as a replication slave and make the index grow as the database slowly gets synced with the "master". This seems to work, even though it's not extremely fast.
