### ISSUE TITLE
Couchdb 2.0 support

### ISSUE THREAD

**Issue by chaitanya9186** [rnewson/couchdb-lucene#236]
Thanks for the good work.

I know there are very few changes from couchdb 1.x to couchdb 2.0 w.r.t this feature.

But I have couple questions:
1. In new Couchdb 2.0, the multi-master clustering is supported, that means one database can be present in couple of nodes, in other words only part of the database is stored in one node. How couchdb-lucene will work in this case? 
2. Can we able to create a cluster couchdb-lucene cluster just like couchdb 2.0 cluster independently.

I am fairly new to Couchdb world. I might be using wrong words.

**Comment by rnewson** [comment]
hi. first thing, there are some bugs in couchdb-lucene around couchdb 2.0 support. I have not had time yet to fix them.

1. couchdb-lucene will index the full database, it is is not a clustered search solution.
2. nope, sorry.

you can use the clouseau/dreyfus software that I wrote for Cloudant and which powers their Search 2.0 offering if you want a search cluster solution, see https://cloudant.com/blog/enable-full-text-search-in-apache-couchdb/ for details.

**Comment by chaitanya9186** [comment]
This is great.
Will clouseau/dreyfus scale like couchdb 2.0?
If I want to use this, Do I need to compile the whole couchdb system?

**Comment by rnewson** [comment]
it's the same code as Cloudant uses, so yes. :)

You will need to compile couchdb from source to get this to work, I wish it were easier.

**Comment by chaitanya9186** [comment]
Thank you @rnewson.

**Comment by dmunch** [comment]
@chaitanya9186 I just followed the cloudant article and managed to get couchdb with dreyfus compiled and running, so if you're having any questions I'm happy to help. 

@rnewson In a nutshell, comparing couchdb-lucene to dreyfus, is it that dreyfus scales with the number of clusters (Looking at the dreyfus code it looks like each instance of clouseau only indexes the shards of the corresponding node?). whereas couchdb-lucene would have a harder time to scale? Are there any other characteristics which differentiate couchdb-lucene form dreyfus/clouseau? (Besides the more recent version of Lucene).

**Comment by chaitanya9186** [comment]
Thanks @dmunch. If possible could you share the repo or docker file.

@rnewson Are there any plans to upgrade  clouseau/dreyfus to latest version?

**Comment by rnewson** [comment]
no immediate plans to do so.

**Comment by chaitanya9186** [comment]
@rnewson, Could you give a brief intro on clouseau and couchdb-lucene.

I the difference I got from looking into code is that, clouseau will be deployed to every node and documents are pushed / pulled by dreyfus but couchdb-lucene will be deployed to every node (or can be deployed to single node as well) and documents are pushed through changes_ listener and indexing code and pulled through proxy api.

Please correct me.

**Comment by dmunch** [comment]
@chaitanya9186 I just pushed a branch with the changes from the article merged into current couchdb master: https://github.com/dmunch/couchdb/tree/dreyfus - Starting from there, if you use the standard build-instructions dreyfus gets compiled as well. You still need to run clouseau like explained in the article.

**Comment by rnewson** [comment]
@chaitanya9186 that's right. 

a couchdb-lucene  server will index the entire database, whereas the clouseau/dreyfus setup will index the individual shards and then join them together at query time.

**Comment by dmunch** [comment]
I'm currently looking into both alternatives as well, and I agree a small overview with pros/cons of each approach would be nice given that CouchDb 2.0 with dreyfus starts to be a thing.

So basically so far I could come up with

dreyfus:
PROS: 
- Scales the same way as CouchDb 2 does
- Integrates nicely with Mango

CONS:
- Stuck with Lucene 4.x on Java 6 for the middle to long term

couchdb-lucene:
PROS: 
- Gives you the latest and gratest Lucene 6.x / Java 8
- Looks easier to extend for custom scenarios (kd-trees etc.)

CONS:
- Integrates less nicely
- Doesn't scale


Is that about it? Or are there things I've overseen so far? I guess I should get into prototyping with our application to see exactly what kind of scenarios I can achieve with each one.

**Comment by rnewson** [comment]
That's a fair summary, yes. 

I don't have much time to work on either right now but I do want to improve both projects.

**Comment by chaitanya9186** [comment]
I like the idea of scaling with Couchdb 2.0, which feels like a plausible approach going forward. I would love work on the migration of clouseau to lucene 6 adding any missing features. 

I will keep some time this next week in understanding the code.
Thank you

**Comment by rnewson** [comment]
lucene 6 requires jdk 8 iirc, and the components that clouseau uses (scalang) won't work with that. perhaps they can all be updated though.

**Comment by dmunch** [comment]
Fools seldom differ, I kind of got the same feeling as @chaitanya9186 - I had a first look on the dependency list and it went deep down the rabbit hole: Not only scalang and its transitive dependencies need to be updated to run on jdk 8, also scala itself only seems to be fully embracing Java 8 with version 2.12 which still is in RC state. Given that I never wrote single line of Scala I quickly resigned on getting my hands dirty.

**Comment by chaitanya9186** [comment]
I also found the same, lets wait for Scala to come up with jdk 8 support first, later we can do a clouseau migration followed by scalang migration.

**Comment by chaitanya9186** [comment]
I have created an [issue #4](https://github.com/cloudant-labs/clouseau/issues/4) in clouseau repo to track the migration.

**Comment by rnewson** [comment]
awesome :)

**Comment by rnewson** [comment]
just pushed an update for couchdb 2.0 compatibility.
