### ISSUE TITLE
custom analyzers?

### ISSUE THREAD

**Issue by drupchen** [rnewson/couchdb-lucene#245]
We are developing custom analyzers that we will use alongside the ones provided, but it looks like we have to modify the [Analyzers.java](https://github.com/rnewson/couchdb-lucene/blob/master/src/main/java/com/github/rnewson/couchdb/lucene/util/Analyzers.java).
They are not enough stable at the moment to propose to add them to the supported list.

We would like to have the possibility to add them to a configuration file instead. Would that be possible?

Many thanks!

**Comment by rnewson** [comment]
I'd review a PR to make it configuration driven but it's not something I'll develop myself.

**Comment by xristy** [comment]
I've opened [PR #249](https://github.com/rnewson/couchdb-lucene/pull/249) to cover the various comments made on [PR #247](https://github.com/rnewson/couchdb-lucene/pull/247)

**Comment by xristy** [comment]
This issue is resolved by PR 249
