### ISSUE TITLE
Index view design document in couchdb-lucene

### ISSUE THREAD

**Issue by wonderfuljamesjin** [rnewson/couchdb-lucene#256]
Hi @rnewson,

One question need you more clarify more information,  if the _design/indexview design document in couchdb is involved at runtime? what I want to know is what role the index view definition plays in the whole process. 

Thanks a lot for your help

**Comment by wonderfuljamesjin** [comment]
Also is there a diagram showing relationship among couchdb, design index view,  couchdb-lucene? thank you

**Comment by rnewson** [comment]
hm, no, but it's fairly simple. couchdb and couchdb-lucene are both servers and are configured to talk to each other. the _fti configuration is optional, you could call couchdb-lucene directly.
