### ISSUE TITLE
Configuration for CouchDB 2.3.0

### ISSUE THREAD

**Issue by misilot** [rnewson/couchdb-lucene#273]
Hi, can the readme be updated to show how to enable the connection now that in 2.3.0 [httpd_db_handlers] has been removed from the configuration? Thanks!

**Comment by gstilman** [comment]
@misilot Did you every figure this out? Getting 500 errors

**Comment by misilot** [comment]
@gstilman from what I can tell is support for httpd_db_handlers is not available in 2.3.x. 

So what we ended up doing is a proxy pass in apache directly to the lucene endpoint instead of proxying through couchdb.

**Comment by rnewson** [comment]
yes, that's right. That degree of pluggability was removed due to repeated security issues with it.

**Comment by andreyvk** [comment]
@misilot could you please elaborate on that last comment about the "proxy pass in apache directly"? We're having hard time making couchdb 2.3.1 talk to couchdb-lucene. This is pretty much the only post available that looks like our problem and there's no concrete steps listed )

@rnewson could you also suggest smth. The documentation doesnt seem to be correct. I've tried various ways to no avail

**Comment by misilot** [comment]
@andreyvk Something like this in our apache config. Where couchdb-lucene is listening on port 5985, so we can access it via http://webserver/_fti/   and than pass any arguments you would have done to couch after the last /

```    <IfModule proxy_http_module>
      ProxyPreserveHost On
      ProxyPassMatch "/_fti/(.*)$" "http://localhost:5985/$1" timeout=30
      ProxyPassReverse "/_fti/(.*)$" "http://localhost:5985/$1" timeout=30
    </IfModule>```

**Comment by andreyvk** [comment]
Thank you so much! Let me try that.
