### ISSUE TITLE
Does couchdb-lucene offer faceting features, like counts etc?

### ISSUE THREAD

**Issue by ykodgule** [rnewson/couchdb-lucene#275]
If I have a field say "category" in all the documents, and the values of this field may vary between 10 different values. I would like to fetch the counts of each category type. 
Does couchdb-lucene support this faceting? If yes, please suggest how can I use it?

**Comment by rnewson** [comment]
Sorry, it does not.

**Comment by sansato** [comment]
map/reduce index can give counts like this for entire database, not inside subset of records from arbitrary query.
