### ISSUE TITLE
Using proximity query as fuzzy search

### ISSUE THREAD

**Issue by andreyvk** [rnewson/couchdb-lucene#290]
Hi @rnewson ,

Is there a way to make proximity search behave like the fuzzy one w/o modifying and recompiling the project? The issue is described in full in [this stackoverflow thread](https://stackoverflow.com/questions/68257051/lucene-6-4-couchdb-lucene-fuzzy-search-on-a-token-with-space)

Thanks in advance!

**Comment by rnewson** [comment]
Hi,

Unfortunately, couchdb-lucene doesn't have that ability. I think you would need to extend the query syntax and implement the feature. I would happily review a pull request if you were so inclined.

**Comment by andreyvk** [comment]
Much obliged @rnewson. Thanks!
