### ISSUE TITLE
couchdb-lucene 0.5 does not properly handle databases with '/' in their names

### ISSUE THREAD

**Issue by gws** [rnewson/couchdb-lucene#32]
The problem at least exists when the index is queried, but I think the problem persists throughout, including places where c-l queries CouchDB.

**Comment by inator** [comment]
@rnewson : I'm still seeing this when using with Hoodie (http://hood.ie), which has CouchDB underpinnings.  Hoodie db names include a slash like so:

    user/8479213467799127
even escaping doesn't help:

    http://host/_fti/local/user%2F8479213467799127/_design/lucene/by_title?q=first

I see @janl has contributed recently.  He's a founder of Hoodie and CouchDB genius.  I mentioned him here in case he notices a quick fix (crossing fingers).

**Comment by janl** [comment]
Turns out this was a different thing :)

**Comment by inator** [comment]
Yeah... security.  Thanks - as always - for the help @janl!

**Comment by rnewson** [comment]
:)
